### ISSUE TITLE
Чи є спосіб отримати від Тараса усі відео?

### ISSUE THREAD

**Issue by scsmash3r** [viacheslav-dev-1/cardiogram-of-nation#1]
Дякую за роботу =) Теж збирався робити щось подібне, але якщо наробки вже є, то можна об'єднатись.

Можна було б пережати їх у мінімальну якість та додати до кожного дня. Альтернативні хости є, але потрібен матеріал... Ютуб заблоковано, у Телезі є не все, на Мегого теж не все.

Є ідеї, як отримати матеріал?

**Comment by viacheslav-dev-1** [comment]
Привіт! Нажаль, про відео як їх добути не знаю. Можливо запитати у Тараса,
щоб їх кудись вигрузив, проте я не став це робити, оскільки він воює і часу
не так багато є, тому не став питати. А так, об'єднатись можна звичайно)

пт, 24 лют. 2023 р. о 19:36 Eugene Esca ***@***.***> пише:

**Comment by scsmash3r** [comment]
Ото я теж не хочу зайвий раз відволікати пана Тараса щодо віртуалу. 
Добре, я спочатку спробую щось пошукати по своїм джерелам, і можливо будуть якісь пул-реквести - а там вже подивимось, що як.

**Comment by scsmash3r** [comment]
Ок, знайшов сорс. Тепер треба все викачати. Тарас робить 2 відео: одне зранку, друге - ввечері. Поки що викачав першу сотню, відібрав спецвипуски та поєднав 2 відео в одне ціле + рескейлінг + пережата на мінімум якість, щоб тим, у кого поганенький мобільний інтернет, теж могли швиденько дивитися.

Як буде готово, закину у json форматі.

Бачу, що сама база знаходиться у firebase, щоб юзери бачили оновлення якомога швидше, без зайвих деплоїв з боку гіта, тощо. Чи є там якась json schema у набору даних, щоб я зорієнтувався, які вже ключі є, і який додати? Поки що побачив такі:

```
  {
    "id": "string",
    "day": "int",
    "line": "int",
    "cFeel": "string",
    "sFeel": "string",
    "eFeel": "string",
    "cZero": "bool",
    "trigger": "string",
    "cLine": "int",
    "sLine": "int"
  }
  ```
  
Щось забув? Якщо ні, додам сюди ще посилання на відео (ну або можна їх окремо зробити). Коротше, якось уніфікувати дані треба, щоб з ними можна було працювати.

**Comment by viacheslav-dev-1** [comment]
Привіт. Так, структура така. Тільки, якщо, наприклад, немає зеро-поінта, то
при заповненні БД я не вписую поле cZero в джсон. Так само, якщо лінія
стану однакова і у цивільних і у військових, то так само не вношу поля
cLine, sLine . Тобто основна структура це:
{
   "id": "string",
   "day": "int",
   "line": "int",
    "cFeel": "string",
    "sFeel": "string",
    "eFeel": "string",
     "trigger": "string"
}

"trigger" - це події, які так чи інакше впливали на стан в конкретно взятий
день згідно відео.

сб, 25 лют. 2023 р. о 21:40 Eugene Esca ***@***.***> пише:

**Comment by scsmash3r** [comment]
Не зміг ніде знайти (але воно точно було на ютубі):
День 189 Чому побільшало сварок?
День 191 Стан втоми і НЕочевидні причини
День 209 Нові кумедні плани і ІПсО мрійників-дегенератів
День 219 Один з найскладніших станів цивільнтх через дії терористів. Зеро-поінт
День 220 Чули щось про персеверацію?
День 224 Важливо стрес цивільних не перекласти на сфокусованість військових
День 225 Новий стан цивільних - гоміцидоманія
День 234 Вплив волонтерства на всі емоційні стани
День 235 Спостереження і зухвалість. Вплив культури на стани сьогодні
День 237 Стани цивільних і військових різні. Що означає «злість»?
День 239 Депресивність цивільних і тиск на військових. Що робити і чим загрожує
День 244 ?
День 272 Хтось вгадає що буде далі?
День 286 Шо, день ЗСУ підіймає настрій, да?
День 287 Чому закордонні ЗМІ не втомляться писати про Україну?
День 288 І хто там боявся, що з боку світових ЗМІ Україні поменшає уваги?
День 289 ?
День 301 Гордість
День 302 100 тисяч підняли настрій? Зізнавайтесь 
День 303 Україна на передових шпальтах, але емоційно знижуємося
День 304 Апатія цивільних пов‘язана зі святами
День 316 Хароші цифри. Дуже хароші
День 317 Шо по зброї? Рефлекси страху
День 327 Емпатія українців зашкалила
День 331 ?
День 332 Як працюють ворожі ІПсО і як це впливає на танки

Усе інше у процесі ре-енкодінгу, щоб відяшки були на швидкості x2 та мали якомога меньший розмір.

**Comment by viacheslav-dev-1** [comment]
Чудово. Дуже дякую!

нд, 26 лют. 2023 р. о 16:02 Eugene Esca ***@***.***> пише:

**Comment by scsmash3r** [comment]
Ок, нарешті завантажено: https://archive.org/details/taras_bilka_bilchenia-cardiogram_of_ukraine_nation

Якщо б оригінали завантажував, напевно чекав би десь місяць... =)
Ще потім закину на мегу.

Тепер діло за перегляданням відяшок та виписуванням відсутніх на графіку станів.

Internet Archive дозволяє embed, тож на самій кардіограмі можна або зробити маленьку картинку типу 32х32 там, де закінчується стовбець із цяточками і починаються наліпки (між ними), або під наліпками.

Ну або ж варіант, коли click на цифру із днем + коли click на сам кружечок на графіку (по hover'у перетворювати його на play icon). Може візуалізую, як час буде.

**Comment by viacheslav-dev-1** [comment]
Дякую! Потроху буду заповнювати прогалини. А по перегляду відосів ще
подумаю, якщо матимеш пропозиції, то скинеш будь-ласка, я теж подумаю, як
краще буде

вт, 28 лют. 2023 р. о 05:02 Eugene Esca ***@***.***> пише:
